#!/bin/sh
set -e

case "$1" in
    configure)
        if [ "$2" = "" ] && [ -d /run/systemd/system ]; then
            if command -v deb-systemd-helper >/dev/null 2>&1; then
                deb-systemd-helper enable subcli-daemon.service >/dev/null 2>&1 || true
            fi
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        ;;
esac
