#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            if command -v deb-systemd-helper >/dev/null 2>&1; then
                deb-systemd-helper stop subcli-daemon.service >/dev/null 2>&1 || true
            fi
        fi
        ;;
    failed-upgrade)
        ;;
    *)
        ;;
esac
