# Post-install cleanup: remove openssl artifacts leaked by FetchContent
# Runs at install time via install(SCRIPT)

set(_destdir_ "$ENV{DESTDIR}")
set(_prefix_ "${CMAKE_INSTALL_PREFIX}")

if(_destdir_ AND NOT _destdir_ STREQUAL "")
  set(_root_ "${_destdir_}")
else()
  set(_root_ "${_prefix_}")
endif()

foreach(_base_ "${_root_}${_prefix_}" "${_root_}" "${_root_}/../")
  # Remove openssl headers
  set(_inc_ "${_base_}/include/openssl")
  if(EXISTS "${_inc_}")
    file(REMOVE_RECURSE "${_inc_}")
    message(STATUS "Cleaned include/openssl")
  endif()
  # Remove openssl static libs
  foreach(_lib_ "libcrypto.a" "libssl.a")
    set(_static_ "${_base_}/lib/${_lib_}")
    if(EXISTS "${_static_}")
      file(REMOVE "${_static_}")
      message(STATUS "Cleaned lib/${_lib_}")
    endif()
    set(_static_ "${_base_}/usr/lib/${_lib_}")
    if(EXISTS "${_static_}")
      file(REMOVE "${_static_}")
      message(STATUS "Cleaned usr/lib/${_lib_}")
    endif()
  endforeach()
  # Remove openssl pkgconfig
  if(EXISTS "${_base_}/lib/pkgconfig")
    file(GLOB _pcs_ "${_base_}/lib/pkgconfig/*openssl*" "${_base_}/lib/pkgconfig/*ssl*" "${_base_}/lib/pkgconfig/*crypto*")
    if(_pcs_)
      file(REMOVE ${_pcs_})
      message(STATUS "Cleaned pkgconfig openssl files")
    endif()
  endif()
  # Remove openssl docs
  if(EXISTS "${_base_}/share/doc/man1")
    file(GLOB _ossl_doc_ "${_base_}/share/doc/man1/*openssl*" "${_base_}/share/doc/openssl*" "${_base_}/share/doc/HOWTO")
    if(_ossl_doc_)
      file(REMOVE ${_ossl_doc_})
    endif()
  endif()
  # Remove openssl share data
  set(_sosl_ "${_base_}/share/openssl")
  if(EXISTS "${_sosl_}")
    file(REMOVE_RECURSE "${_sosl_}")
    message(STATUS "Cleaned share/openssl")
  endif()
  # Remove any libcrypto/libssl (dylib on macOS)
  file(GLOB _ssl_so_ "${_base_}/lib/libssl*" "${_base_}/lib/libcrypto*")
  if(_ssl_so_)
    file(REMOVE ${_ssl_so_})
    message(STATUS "Cleaned libssl/libcrypto shared libraries")
  endif()
endforeach()
